<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestngAnnotation.TestSodtAssertion" tests="2" time="0.029" ignored="0" failures="1" timestamp="13 Jun 2023 06:44:49 GMT" skipped="0" hostname="SYPULCP7CWG3" errors="0">
  <testcase name="testSoftAssert" time="0.029" classname="TestngAnnotation.TestSodtAssertion"/>
  <testcase name="afterTest" time="0.000" classname="TestngAnnotation.TestSodtAssertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1],
	expected [false] but found [true],
	null,
	expected [Kajal] but found [Nidhi],
	expected [Kajal1] but found [Nidhi1]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestngAnnotation.TestSodtAssertion.afterTest(TestSodtAssertion.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- afterTest -->
</testsuite> <!-- TestngAnnotation.TestSodtAssertion -->
